services:
  jupyter:
    container_name: jupyter-tensorflow-gpu
    image: tf-gpu-jupyter
    build:
      context: .
      dockerfile: Dockerfile_tf
    volumes:
      - "./notebooks:/tf/notebooks"
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]